# site settings

title: Joseph Asplet
description: Postdoctoral researcher in induced seismicity and seismic imaging
taglong: Research Seismologist
tagshort: Seismologist
url: https://jasplet.github.io
baseurl: ""
permalink: Jasplet
repo: https://github.com/Jaspelt/jasplet.github.io

# author settings

author:
  name: Joseph Asplet
  email: joseph.asplet@earth.ox.ac.uk
photo: /assets/jpg/JA_AGU_headshot.jpg

# social media links

social:
  github: Jasplet
  linkedin: Joseph-asplet
# Academic profile links

academic:
  orcid: 0000-0002-0375-011X
  google-scholar: https://scholar.google.com/citations?user=TUbu_1AAAAAJ&hl=en
# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
