# site settings

title: Joseph Asplet
description: Postodoctoral research in induced seismicity and seismic imaging
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme
url: https://jasplet.github.io
baseurl: ""
permalink: Jasplet
repo: https://github.com/Jaspelt/jasplet.github.io

# author settings

author:
  name: Joseph Asplet
  email: joseph.asplet@earth.ox.ac.uk
photo: /assets/jpg/JA_AGU_headshot.jpg

# social media links

social:
  github: Jasplet
  orchid: 0000-0002-0375-011X

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
